import test from "node:test";
import assert from "node:assert/strict";
import { GeminiVoice, OpenAIVoice } from "../dist/providers/index.js";
import { PcmEncoder, pcmFloat } from "../dist/pcm.js";
import { CameraSession } from "../dist/camera.js";
import { survey, context, deferred, fakeStream, wait } from "./fixtures.mjs";
const q = survey.questions[0];
function gemini(extra = {}) {
  const stream = fakeStream(); const sent = []; let callbacks; const session = { closed: 0, close() { this.closed++; }, sendClientContent(v) { sent.push(v); }, sendRealtimeInput() {}, sendToolResponse() {} };
  const io = { closed: 0, busy: false, activate: async () => {}, capture: async () => {}, play() {}, clear() { this.busy = false; }, close() { this.closed++; } };
  const voice = new GeminiVoice({ startSession: async () => ({ provider: "gemini", token: "auth_tokens/test-only", model: "fixture" }), modelKey: "voice", getMicrophone: async () => stream, createAudioIO: () => io, connectLive: async (_token, _model, _config, value) => { callbacks = value; return session; }, ...extra });
  return { voice, stream, io, session, sent, get callbacks() { return callbacks; } };
}
const connect = voice => voice.connect(context, q, {}, () => {}, new AbortController().signal);
test("PCM output is little-endian and clamps both extrema", () => { const encoder = new PcmEncoder(16000), bytes = encoder.push(new Float32Array([-2, 0, 2])); assert.deepEqual([...bytes], [0,128,0,0,255,127]); assert.ok(pcmFloat(bytes)[2] > .99); });
test("resampling preserves phase across arbitrary browser worklet chunk boundaries", () => { const input = Float32Array.from({ length: 4410 }, (_, i) => Math.sin(i / 15)); const whole = new PcmEncoder(44100).push(input), encoder = new PcmEncoder(44100), pieces = []; for (let i = 0; i < input.length; i += 128) pieces.push(...encoder.push(input.subarray(i, i + 128))); assert.deepEqual(pieces, [...whole]); assert.equal(whole.length, 3200); });
test("Gemini microphone arriving after cancellation is stopped immediately", async () => { const pending = deferred(), stream = fakeStream(), g = gemini({ getMicrophone: () => pending.promise }); const p = connect(g.voice); await wait(); g.voice.disconnect(); pending.resolve(stream); await assert.rejects(p); assert.equal(stream.track.stopped, 1); assert.ok(g.io.closed > 0); });
test("Gemini session resolving after cancellation is closed and cannot capture audio", async () => { const pending = deferred(), late = { closed: 0, close() { this.closed++; } }, g = gemini({ connectLive: () => pending.promise }); const p = connect(g.voice); await wait(); g.voice.disconnect(); pending.resolve(late); await assert.rejects(p); assert.equal(late.closed, 1); assert.ok(g.stream.track.stopped > 0); });
test("Gemini connect failure releases microphone and audio context", async () => { const g = gemini({ connectLive: async () => { throw new Error("fixture failure"); } }); await assert.rejects(connect(g.voice)); assert.ok(g.stream.track.stopped > 0); assert.ok(g.io.closed > 0); });
test("Gemini startup timeout closes resources before a late SDK result arrives", async () => { const pending = deferred(), late = { closed: 0, close() { this.closed++; } }, g = gemini({ connectLive: () => pending.promise, timeoutMs: 5 }); const p = connect(g.voice); await wait(15); assert.ok(g.stream.track.stopped > 0); pending.resolve(late); await assert.rejects(p); assert.equal(late.closed, 1); });
test("Gemini context sharing is silent and refuses to interrupt active output", async () => { const g = gemini(); await connect(g.voice); assert.equal(g.voice.updateContext("fixture context"), true); assert.equal(g.sent[0].turnComplete, false); g.callbacks.onmessage({ serverContent: { modelTurn: { parts: [{ inlineData: { data: "AAA=", mimeType: "audio/pcm" } }] } } }); assert.equal(g.voice.updateContext("second"), false); g.voice.disconnect(); });
test("Gemini final transcripts include both roles and maintain their original revision", async () => {
  const g = gemini(), events = []; await g.voice.connect(context, q, {}, e => events.push(e), new AbortController().signal);
  g.callbacks.onmessage({ serverContent: { inputTranscription: { text: "週末", finished: false } } }); g.voice.setRevision({ ...context, revision: 2 });
  g.callbacks.onmessage({ serverContent: { inputTranscription: { text: "がいいです", finished: true }, outputTranscription: { text: "了解です", finished: true }, turnComplete: true } });
  const transcripts = events.filter(e => e.type === "transcript" && e.transcript.final); assert.equal(transcripts[0].transcript.text, "週末がいいです"); assert.equal(transcripts[0].transcript.context.revision, 1); assert.equal(transcripts[1].transcript.role, "assistant"); g.voice.disconnect();
});
test("Gemini disconnect and goAway clear media even if SDK close fails", async () => { const g = gemini(); await connect(g.voice); g.session.close = () => { throw new Error("fixture failure"); }; g.callbacks.onmessage({ goAway: { timeLeft: "1s" } }); assert.ok(g.stream.track.stopped > 0); assert.ok(g.io.closed > 0); });
function openai(extra = {}) {
  const stream = fakeStream(), messages = [];
  const channel = { readyState: "connecting", send: text => messages.push(JSON.parse(text)), close() { this.readyState = "closed"; } };
  const peer = new EventTarget(); Object.assign(peer, { iceGatheringState: "complete", connectionState: "new", closed: 0, createDataChannel: () => channel, addTrack() {}, createOffer: async () => ({ type: "offer", sdp: "v=0\r\nfixture" }), setLocalDescription: async function(value) { this.localDescription = value; }, setRemoteDescription: async () => { channel.readyState = "open"; channel.onopen?.(); }, close() { this.closed++; } });
  const audio = { srcObject: null, play: async () => {}, pause() {}, autoplay: false };
  const voice = new OpenAIVoice({ startSession: async () => ({ provider: "openai", sdp: "v=0\r\nfixture" }), modelKey: "voice", getMicrophone: async () => stream, createPeer: () => peer, createAudio: () => audio, ...extra });
  return { voice, stream, channel, peer, audio, messages };
}
test("OpenAI microphone arriving after cancellation is stopped", async () => { const pending = deferred(), stream = fakeStream(), o = openai({ getMicrophone: () => pending.promise }); const p = connect(o.voice); await wait(); o.voice.disconnect(); pending.resolve(stream); await assert.rejects(p); assert.equal(stream.track.stopped, 1); assert.ok(o.peer.closed > 0); });
test("OpenAI SDP failure closes peer/channel/audio and microphone", async () => { const o = openai({ startSession: async () => { throw new Error("fixture failure"); } }); await assert.rejects(connect(o.voice)); assert.equal(o.channel.readyState, "closed"); assert.ok(o.peer.closed > 0); assert.ok(o.stream.track.stopped > 0); assert.equal(o.audio.srcObject, null); });
test("OpenAI context sharing sends only a conversation item, without response.create", async () => { const o = openai(); await connect(o.voice); assert.equal(o.voice.updateContext("fixture context"), true); assert.deepEqual(o.messages.map(m => m.type), ["conversation.item.create"]); o.voice.disconnect(); });
test("OpenAI old output completion cannot reopen context sharing during respondent speech", async () => {
  const o = openai(), events = []; await o.voice.connect(context, q, {}, e => events.push(e), new AbortController().signal);
  const event = value => o.channel.onmessage({ data: JSON.stringify(value) });
  event({ type: "input_audio_buffer.speech_started", item_id: "u2" }); event({ type: "output_audio_buffer.cleared" }); event({ type: "output_audio_buffer.stopped" }); event({ type: "response.created", response: { id: "old_response" } });
  assert.equal(events.filter(e => e.type === "status").at(-1).status, "user-speaking"); assert.equal(o.voice.updateContext("new context"), false);
  event({ type: "response.function_call_arguments.done", name: "show_sources", call_id: "source_call", arguments: "{}" }); assert.equal(o.messages.some(m => m.type === "response.create"), false);
  event({ type: "input_audio_buffer.speech_stopped" }); event({ type: "output_audio_buffer.stopped" }); assert.equal(o.voice.updateContext("idle context"), true); o.voice.disconnect();
});
test("OpenAI late user transcripts carry the scope captured at speech start", async () => { const o = openai(), events = []; await o.voice.connect(context, q, {}, e => events.push(e), new AbortController().signal); const event = value => o.channel.onmessage({ data: JSON.stringify(value) }); event({ type: "input_audio_buffer.speech_started", item_id: "u1" }); o.voice.setRevision({ ...context, revision: 2 }); event({ type: "conversation.item.input_audio_transcription.completed", item_id: "u1", transcript: "週末" }); assert.equal(events.find(e => e.type === "transcript").transcript.context.revision, 1); o.voice.disconnect(); });
test("camera requires explicit consent before any media request", async () => { let calls = 0; const c = new CameraSession({ pause() {}, srcObject: null }, { observe: async () => {}, onObservation() {}, getCamera: async () => { calls++; return fakeStream(); } }); await assert.rejects(c.start(false)); assert.equal(calls, 0); });
test("camera permission resolving after stop releases the late media track", async () => { const pending = deferred(), stream = fakeStream(); const c = new CameraSession({ pause() {}, play: async () => {}, srcObject: null }, { observe: async () => {}, onObservation() {}, getCamera: () => pending.promise }); const p = c.start(true); c.stop(); pending.resolve(stream); await p; assert.equal(stream.track.stopped, 1); });
test("camera stop aborts observation, clears preview and suppresses a late result", async () => { const pending = deferred(), stream = fakeStream(), seen = []; let signal; const video = { srcObject: null, pause() {}, play: async () => {} }; const c = new CameraSession(video, { observe: (_jpeg, s) => { signal = s; return pending.promise; }, onObservation: value => seen.push(value), getCamera: async () => stream, captureFrame: () => "fictional-frame" }); await c.start(true); await wait(); c.stop(); assert.equal(signal.aborted, true); assert.equal(video.srcObject, null); assert.ok(stream.track.stopped > 0); pending.resolve({ light: "bright", clarity: "clear", material: "present", face: "none", observedAt: Date.now() }); await wait(); assert.equal(seen.filter(Boolean).length, 0); });
